#!/usr/bin/env python

import sys

buff = []
for line in sys.stdin.readlines():
	if line[0] == '#' or line[0:2] == '/*' or line[0:13] == 'SET TIMESTAMP':
		buff.append(line)
	else:
		print '\033[31m' + line + '\033[0m', buff
		buff = []